---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
```

```{r}
files <- list.files('../../data/extracted', full.names = TRUE) %>% set_names(basename(.) %>% str_remove('.csv'))
files
```


```{r}
column_names <- c('Specialty',
                  'No. of Programs',
                  'Positions Offered',
                  'Unfilled Programs',
                  'MD Senior Applicants',
                  'Total Applicants',
                  'MD Senior Matches',
                  'Total Matches',
                  'MD Senior % Filled',
                  'Total % Filled',
                  'MD Senior Ranked Positions',
                  'Total Ranked Positions')

merged <- map(files, function(i) {
  dataset <- names(files)[files == i] %>% str_split(' - ') %>% unlist()
  
  read_csv(i, col_names = column_names) %>% 
    mutate(Year = dataset[1],
           Class = dataset[2]) %>% 
    filter(!str_starts(Specialty, 'Total|Specialty')) %>% 
    mutate(across(everything(), as.character)) %>% 
    drop_na()
}) %>% bind_rows()

merged
```

```{r}
merged %>% 
  group_by(Year, Class) %>% 
  tally() %>% 
  pivot_wider(names_from = Class,
              values_from = n)
```


```{r}
merged %>% 
  filter(Specialty == 'Dermatology') %>% arrange(Year) 
  
```
### Long tables
```{r}
long_table_absolute <- merged %>% 
  select(Specialty,
         Year,
         Class,
         `Positions Offered`,
         `MD Senior Applicants`,
         `Total Applicants`,
         `MD Senior Matches`,
         `Total Matches`) %>% 
  pivot_longer(cols = -c(Specialty, Year, Class),
               names_to = 'Name',
               values_to = 'Value') %>% 
  arrange(Specialty, Class, Year)

long_table_absolute
```
```{r}
long_table_percent <-  merged %>% 
  select(Specialty,
         Year,
         Class, 
         `MD Senior % Filled`,
         `Total % Filled`) %>% 
  pivot_longer(cols = -c(Specialty, Year, Class),
               names_to = 'Name',
               values_to = 'Value') %>% 
  arrange(Specialty, Class, Year)

long_table_percent 
```


### Export
```{r}
merged %>% write_tsv('../output/merged_table.tsv')
long_table_absolute %>% write_tsv('../output/long_table_absolute.tsv')
long_table_percent %>% write_tsv('../output/long_table_percent.tsv')
```

